### ISSUE TITLE
Fantastic!

### ISSUE THREAD

**Issue by bubez81** [Arbuzov/home_assistant_delonghi_primadonna#1]
Hello! glad to see someone interested in this coffee machine!
do you think it can work with Dinamica Plus too?
In any case, how is it configured in Homeassistant?
Best regards,
Michele

**Comment by Arbuzov** [comment]
Please check this instruction.
https://github.com/Arbuzov/home_assistant_delonghi_primadonna#configuration
Feel free to ask any questions.

**Comment by bubez81** [comment]
ah sadly do you use pygatt and not bleak that is cross platform, I'm using macOS ;(

**Comment by Arbuzov** [comment]
As far as I know pygatt is a common library for the HA. Have you any suggestion on a BLE library?

**Comment by bubez81** [comment]
yes I think bleak https://pypi.org/project/bleak/ could be a good choice

**Comment by Arbuzov** [comment]
[1.1.0](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.1.0)

**Comment by bubez81** [comment]
strange...in macOS I receive errors: [custom_components.delonghi_primadonna.device] BleakError: Device with address 00:A0:50:1D:99:27 was not found

**Comment by bubez81** [comment]
I think this is the reason https://bleak.readthedocs.io/en/latest/backends/macos.html

#https://github.com/hbldh/bleak/issues/252
