### ISSUE TITLE
List of Compatible deviced

### ISSUE THREAD

**Issue by GabrieleMandalari** [Arbuzov/home_assistant_delonghi_primadonna#11]
Hello, thanks for your work. Do you have a list of compatible devices with your integration? In addition, I cannot find it via HACS. Why?

Thanks

**Comment by Arbuzov** [comment]
[One can add compatible devices here](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/blob/master/README.md#compartible-devices)

I wish I could test all devices :smiley:
