### ISSUE TITLE
Integration not working after change to HassOS (BleakError: UUID was not found!)

### ISSUE THREAD

**Issue by AirmakZ** [Arbuzov/home_assistant_delonghi_primadonna#19]
Hi !
I was using the integration without problem until I migrated my 'unsupported installation' (Ubuntu) to HassOS.

My current system:
Custom Component version: 1.2.3
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Intel NUC i3

I added the machine MAC address but I can see these two WARNINGS:

Logger: custom_components.delonghi_primadonna.config_flow
Source: custom_components/delonghi_primadonna/config_flow.py:40 
Integration: Delonghi Primadonna (documentation, issues) 
First occurred: 11 October 2022, 20:29:20 (1 occurrences) 
Last logged: 11 October 2022, 20:29:20
Discovered Delonghi device: 00:A0:50:50:7C:62 D1545274       <--- It looks ok since it's the MAC of my machine

Logger: custom_components.delonghi_primadonna.device
Source: custom_components/delonghi_primadonna/device.py:199 
Integration: Delonghi Primadonna (documentation, issues) 
First occurred: 11 October 2022, 20:43:16 (1 occurrences) 
Last logged: 11 October 2022, 20:43:16
BleakError: Characteristic 00035b03-58e6-07dd-021a-08123a000301 was not found!

The second warning appears each few seconds.

Do you have an idea about what could be provoking this connection error?

Thanks in advanced !!!!

**Comment by Arbuzov** [comment]
Could you please check with the latest version?
