### ISSUE TITLE
How to Integrate 

### ISSUE THREAD

**Issue by weldingwit** [Arbuzov/home_assistant_delonghi_primadonna#2]
This looks awesome but how do you integrate it? it does not show up anywhere after installing it?

**Comment by Arbuzov** [comment]
Please check this instruction.
https://github.com/Arbuzov/home_assistant_delonghi_primadonna#configuration
Feel free to ask any questions.

**Comment by weldingwit** [comment]
Thank you managed to integrate however other issues are giving errors same as other user please see below.

https://github.com/Arbuzov/home_assistant_delonghi_primadonna/issues/3#issuecomment-1183138258
