### ISSUE TITLE
Add support for ECAM 650.85.MS

### ISSUE THREAD

**Issue by bakteriak** [Arbuzov/home_assistant_delonghi_primadonna#20]
Hi!

I hope support for ECAM 650.85.MS can be added for this integration.

It is not listed on compatible devices

Thanks in advance

**Comment by Arbuzov** [comment]
Please check [1.2.4](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.2.4) if that was expected please close PR
