### ISSUE TITLE
Delonghi Dedica 370.95 not connected

### ISSUE THREAD

**Issue by tomfool1985** [Arbuzov/home_assistant_delonghi_primadonna#26]
Hi there,

The integration found the machine but right after is not more able to connect to the machine?

Any reason why?

Thanks

**Comment by tomfool1985** [comment]
this is the log:

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.delonghi_primadonna.device
Source: custom_components/delonghi_primadonna/device.py:276
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 24 novembre 2022 18:31:24 (4756 occurrences)
Last logged: 16:45:53

BleakError: Bluetooth GATT Error address=00:A0:50:12:E3:1F handle=3 error=133 description=Error
BleakError: Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish
BleakError: Error while reading data: 0 bytes read on a total of 1 expected bytes
BleakError: Error ESP_GATT_CONN_TIMEOUT while connecting: Connection failed due to timeout
BleakError: A device with address 00:A0:50:12:E3:1F could not be found.

**Comment by d-lebed** [comment]
Same here. It found the machine but is not able to turn it on, etc...

**Comment by codyc1515** [comment]
Could you please try it again on latest HA and let us know how you get on? HA made signifcant improves to BLE in the past few months. Please also check you are using a supported dongle.

**Comment by tomfool1985** [comment]
> Could you please try it again on latest HA and let us know how you get on? HA made signifcant improves to BLE in the past few months. Please also check you are using a supported dongle.

it works now!

**Comment by codyc1515** [comment]
Woohoo. Can you please close the ticket?

**Comment by tomfool1985** [comment]
solved with the last version of H.A
