### ISSUE TITLE
BleakDBusError / TimeoutError 

### ISSUE THREAD

**Issue by mannipulator** [Arbuzov/home_assistant_delonghi_primadonna#27]
Hi, I get since a few days permanently the following two errors and the coffee machine (Delonghi Primadonna) can no longer be controlled via Home Assistant

Issue 1:
------------------------------------------------------------------

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.delonghi_primadonna.device
Source: custom_components/delonghi_primadonna/device.py:273
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 29. November 2022 um 22:00:55 (2134 occurrences)
Last logged: 10:52:02

BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local
BleakDBusError: [org.bluez.Error.Failed] br-connection-canceled

Issue 2:
------------------------------------------------------------------

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.delonghi_primadonna.device
Source: custom_components/delonghi_primadonna/device.py:279
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 29. November 2022 um 22:00:29 (282 occurrences)
Last logged: 10:51:51

TimeoutError:

The integration worked very well for a few weeks / months. Does anyone have any idea ?

**Comment by Arbuzov** [comment]
Please try with the new Home assistant OS.
New Bleak version were included it makes all integration more stable.
