### ISSUE TITLE
Turn Off

### ISSUE THREAD

**Issue by oneseventhree** [Arbuzov/home_assistant_delonghi_primadonna#28]
Amazing Integration! This sold me on the machine so Delonghi should be paying you! haha

Is there an option to turn off the machine?

**Comment by Arbuzov** [comment]
Thanks. I could not find a turn off command at any public spec available.
Moreover I could not find it by brute force sending data.
Also I could not find turn off button at android app, so I can`t sniff the traffic.

If anyone will be able to find the command, I will be appreciated,

**Comment by codyc1515** [comment]
If it’s not possible from the app, it’s not going to be possible for us. Unfortunately for now I don’t think we will be able to do this.

**Comment by Arbuzov** [comment]
@codyc1515 is absolutely right
There is no way to turn off the machine.

**Comment by DavidAntonin** [comment]
In the first versions of the app, it was possible to turn off the coffee machine. I tried to download it from Apkpure, unfortunately after starting it writes about a problem with the internet connection - probably it needs to communicate with the Delongi server, which in the meantime has adapted to the new versions. Just shutting it down would be a useful feature. But thanks for the development anyway.
