### ISSUE TITLE
Problem with the integration as of HA Version 2023.3

### ISSUE THREAD

**Issue by boekerolli** [Arbuzov/home_assistant_delonghi_primadonna#38]
Hi Sergey,
I get the following log entries...
Can you please have a look at this?
Thank you and best regards,
Olli
*****************************************************************************************

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 09:45:13 (1 occurrences)
Last logged: 09:45:13

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for delonghi_primadonna using this method at custom_components/delonghi_primadonna/__init__.py, line 25: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

*****************************************************************************************
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.delonghi_primadonna.config_flow
Source: custom_components/delonghi_primadonna/config_flow.py:40
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 09:56:03 (1 occurrences)
Last logged: 09:56:03

Discovered Delonghi device: xx:xx:xx:xx:xx:xx D1531999

*****************************************************************************************
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/delonghi_primadonna/device.py:207
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 09:56:02 (9 occurrences)
Last logged: 09:56:29

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/delonghi_primadonna/device.py", line 207, in _handle_data
    self.steam_nozzle = NOZZLE_STATE.get(value[4], value[4])
IndexError: bytearray index out of range

**Comment by Arbuzov** [comment]
Thanks for the information
