### ISSUE TITLE
Confirmed working with dE'Longhi Eletta Explore 450.65.G

### ISSUE THREAD

**Issue by Minglarn** [Arbuzov/home_assistant_delonghi_primadonna#43]
Works out of the box! :)

**Comment by Arbuzov** [comment]
Thanks a lot :)

**Comment by LrdNrtn** [comment]
> Works out of the box! :)

@Minglarn can you please elaborate? afaik Eletta Explore 450.65.G is wifi only

**Comment by Minglarn** [comment]
It works.. connect your delonghi to your personal wifi and the Home Assistant will find it.

**Comment by damitch300** [comment]
> It works.. connect your delonghi to your personal wifi and the Home Assistant will find it.

Well i did this but HA wont find it. How did you add the Mac? I tried every possible way but no device found
