### ISSUE TITLE
Unable to connect Coffee Link models?

### ISSUE THREAD

**Issue by zuohaot** [Arbuzov/home_assistant_delonghi_primadonna#47]
Firstly, thank you for the great work!

My machine is ECAM450.86.T with the "Coffee Link" mobile app control capability (https://www.delonghi.com/en-au/eletta-explore-automatic-coffee-machine-ecam450-86-t/p/ECAM450.86.T). 

I tried to search for the ble mac address. However, I was not able to find my machine.

There is a MAC address shown on the touch screen of my machine. However, it did not work. Anyone can help? TIA!
<img width="418" alt="image" src="https://user-images.githubusercontent.com/56582980/235015519-f2b00706-dfe6-433f-b09b-08823dfeb024.png">

**Comment by Arbuzov** [comment]
This integration is for the bluetooth device only
