### ISSUE TITLE
Blocking call to sleep inside the event loop WARNING

### ISSUE THREAD

**Issue by AirmakZ** [Arbuzov/home_assistant_delonghi_primadonna#5]
Hi Sergey

Just in case you didn't notice it, Home Assistant is showing a warning with the following data.
As you can see it just a warning but maybe there is a way to improve it !

WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for delonghi_primadonna doing blocking calls at custom_components/delonghi_primadonna/device.py, line 247: data = self._device.char_read()

WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for delonghi_primadonna doing blocking calls at custom_components/delonghi_primadonna/device.py, line 113: self._adapter.stop()

Thanks for your work in the integration.

**Comment by Arbuzov** [comment]
[1.1.0](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.1.0)
