### ISSUE TITLE
Primadonna elite stopped working

### ISSUE THREAD

**Issue by minaghopreal** [Arbuzov/home_assistant_delonghi_primadonna#50]
Greetings,

I am a complete newbie when it comes to home assistant and coding.
I have used the integration for a while. It has been a hit-and-miss but mostly working.

For the past few days, It has stopped working completely. I deleted the integration, automatically discovered the machine but It never works.

See the log (If I did that right)
I understand if you are busy to respond, and thanks in advance to whoever spared a minute to reply

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/delonghi_primadonna/__init__.py:25
Integration: Delonghi Primadonna (documentation, issues)
First occurred: 3:14:35 PM (1 occurrences)
Last logged: 3:14:35 PM

Error setting up entry Coffee Machine for delonghi_primadonna
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/delonghi_primadonna/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
`

**Comment by Arbuzov** [comment]
Looks like you updated the home assistant core, but you have not updated the integration.

Please update and let me know.
