### ISSUE TITLE
Bleak not found

### ISSUE THREAD

**Issue by mannipulator** [Arbuzov/home_assistant_delonghi_primadonna#7]
Hi, 

Thanks for this great feature.
After the integration worked great for me for several days, now the following error appears:

Here is my log:
Logger: homeassistant.setup
Source: setup.py:184 
First occurred: 4. August 2022, 08:09:22 (1 occurrences) 
Last logged: 4. August 2022, 08:09:22

Setup failed for custom integration delonghi_primadonna: Requirements for delonghi_primadonna not found: ['bleak==0.14.3'].

**Comment by bubez81** [comment]
The new home assistant release need bleak 0.15.1 but the addon force the system to install the old version

**Comment by mannipulator** [comment]
Okay good to know, but what can I do to get the integration working?

**Comment by bubez81** [comment]
try to do this:
open .homeassistant/custom_components/delonghi_primadonna/manifest.json and change 
 "requirements": ["bleak==0.14.3"],
to
 "requirements": ["bleak>=0.14.3"],

**Comment by mannipulator** [comment]
its working! thank you

**Comment by Arbuzov** [comment]
[1.2.1](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.2.1) should completely remove this issue
